[project]
name = "mushroom"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "semindan", email = "semindan.dev@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.25",
    "openai>=1.77.0",
]

[project.scripts]
mushroom = "mushroom:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
